// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtQVTLxn9XQbGQMlAvWJCoQrqbpS1Bqpk',
    appId: '1:100346183701:web:82457027e0b92c9ea6ce1c',
    messagingSenderId: '100346183701',
    projectId: 'crud-73984',
    authDomain: 'crud-73984.firebaseapp.com',
    storageBucket: 'crud-73984.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1ckfdJ9jpCYxBUBYcoeysBw-h5HDJNKc',
    appId: '1:100346183701:android:230011996764e5bba6ce1c',
    messagingSenderId: '100346183701',
    projectId: 'crud-73984',
    storageBucket: 'crud-73984.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtqvTwZckan6bjByt-ZeriXOj-Cj_XPvk',
    appId: '1:100346183701:ios:38a81f399e797540a6ce1c',
    messagingSenderId: '100346183701',
    projectId: 'crud-73984',
    storageBucket: 'crud-73984.appspot.com',
    iosClientId: '100346183701-u7eva7lvns6qikhso09lb0gcj1d1j799.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtqvTwZckan6bjByt-ZeriXOj-Cj_XPvk',
    appId: '1:100346183701:ios:38a81f399e797540a6ce1c',
    messagingSenderId: '100346183701',
    projectId: 'crud-73984',
    storageBucket: 'crud-73984.appspot.com',
    iosClientId: '100346183701-u7eva7lvns6qikhso09lb0gcj1d1j799.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );
}
